### PR TITLE
Expose generatePath

### PR DESCRIPTION
**Pull request by rybon**
I need this so I can build up parameterized URLs outside of a React component, such as in a saga.

### CODE REVIEW

**Comment by pshrmn** [comment]
I know that the `generatePath.js` file says that this function is public API, but I am fairly certain that that is only because it was copied from `matchPath.js`.

As far as the question of whether or not it should actually be public API goes, I am not sure. I suppose since `matchPath` is already public API, it isn't too crazy to expose this as well.

**Comment by timdorr** [comment]
As a reminder, this was added by #5209 to allow `<Redirect>` to use parameters. It does seem useful as a general utility function, particularly for other downstream routing components folks would like to build.

**Comment by rybon** [comment]
@pshrmn done.

**Comment by MOZGIII** [comment]
Can this be merged?

**Comment by MOZGIII** [comment]
Thanks!

**Comment by MOZGIII** [comment]
Is there a way to use master branch of the code?

**Comment by nickaversano** [comment]
when will this be included in the released versions?

**Comment by timdorr** [comment]
When it's released.

**Comment by jharris4** [comment]
FYI I just created a PR to update `react-router-config` to use this new functionality to support stuff like:

```
let routes = {
  path: "/",
  component: Root,
  routes: [
    {
      path: "/:id",
      redirect: "/home/:id"
    }
    {
      path: "/home/:id",
      component: Home
    }
  ]
}
```

https://github.com/ReactTraining/react-router/pull/6170

**Pull request merged**
