### PR TITLE
Add blocked updates guide to website

### PR DESCRIPTION
**Pull request by pshrmn**
Hopefully people will have an easier time finding this when it is on the site.

### CODE REVIEW

**Comment by pshrmn** [comment]
Added some extra information to the blocked updates guide as well. I have been seeing code that makes quite liberal use of `withRouter` to get around blocks, when they could just receive the `location` as a prop from a parent.

**Comment by timdorr** [comment]
LGTM. Can someone with access to the site merge and push this out?

**Comment by taurose** [comment]
Looks good. Only thing I would change is the `PureComponent` to `sCU => false`. With `this.props.children`, the component would actually not block updates in most scenarios.

**Comment by pshrmn** [comment]
@taurose I just wanted the minimum viable example blocker, which `PureComponent` rendering its `children` provides. I originally did not include the implementation of the `<UpdateBlocker>` (and maybe one doesn't need to be included), but I felt that having a small snippet that says "code that looks like this causes this issue" could be useful.

I had considered using `sCU` in the example, but `sCU => false` would not work. The `sCU` implementation would have return `true` when props change, so it would need to do something like a shallow comparison on the props, but that is essentially re-implementing `PureComponent`.

```js
class UpdateBlocker extends React.Component {
  shouldComponentUpate(nextProps) {
    return !shallowEqual(this.props, nextProps)
  }

  render() {
    return this.props.children
  }
}
```

**Comment by taurose** [comment]
Right, I hadn't thought this through. I agree that `PureComponent` makes more sense than reimpleting it. Still, the (hidden) use of `shallowEquals` on props in combination with `this.props.children` bugs me. How about just rendering a `<ChildComponent />` or `<Route component={ChildComponent} />`?

**Comment by pshrmn** [comment]
I guess that part of the issue is that I use the same fake component name throughout the guide. It makes more sense up above where it is defined because it is just being passed `<NavLink>`s. Down below I'm not actually even passing it any children, which would actually cause an error. I can add a second `<UpdateBlocker>` implementation for that code that makes more sense (probably use a different name as well).

**Comment by pshrmn** [comment]
Still getting a number of issues that are solved by pointing to this. Will be nice once its on the site for increased visibility.

**Comment by timdorr** [comment]
I'm in agreement with getting this in as-is too. Imma merge it. dealwithit.gif. 😎 

@ryanflorence, @mjackson, @tylermcginnis Can any of you push this out to the website? It would *really* help out with the issue load lately.

**Comment by mjackson** [comment]
@timdorr I'm on it. Also, need to do some work on the site so it automatically reflects what's on master.

**Comment by mjackson** [comment]
But at least for now we can point them to the doc on GitHub. This is the main reason I wanted good docs with real links on GitHub; so we don't always have to wait for the site to be updated.

**Pull request merged**
