### PR TITLE
Add useSearchParams hook for convenience [feat-proposal]

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by MeiKatz** [comment]
I think useQuery is ambiguous. Would be better to call it useSearchQuery.

**Comment by caub** [comment]
yea correct, I even use react-query in my project, so I'd have name clashes, ok I updated the namings

**Comment by damikun** [comment]
https://github.com/ReactTraining/react-router/blob/6e13acf6b9c0101bcffb67a236f29226c18c2a6b/packages/react-router-dom/index.tsx#L306

**Comment by caub** [comment]
@damikun Oh nice, ok we'll try to upgrade from v5 to v6, thanks!

**Pull request closed without merging**
