### PR TITLE
add externals config for prop-types?

### PR DESCRIPTION
**Pull request by jochenberger**
I think that you shouldn't package `prop-types` in the UMD modules.

### CODE REVIEW

**Comment by timdorr** [comment]
This is technically proper, but I'm wondering how many people are just importing React/ReactDOM and will have a big breakage when this kind of thing lands.

**Comment by jochenberger** [comment]
I wonder if we could provide a migration path.

**Comment by timdorr** [comment]
It's all or nothing, unfortunately. The only other way around it is to hand-build the UMD version and hack in some sort of externals check to do a deprecation warning if it's not defined externally. But that seems really risky and brittle. 

A minor release with this change shouldn't be a problem. Most UMD consumers should be able to manage their deps in some way, so they should see the requirement for prop-types and add that in.

**Comment by mjackson** [comment]
I think we'll continue to leave `prop-types` in our build for now. Thanks for the suggestion though, @jochenberger :)

**Pull request closed without merging**
