### PR TITLE
bugfix #4292 

### PR DESCRIPTION
**Pull request by dropfen**
withRouter() return wrapped Component if router is not present ([#4292])

### CODE REVIEW

**Comment by timdorr** [comment]
Also, a test for this would be good to add.

**Comment by timdorr** [comment]
Thanks! Just going to wait on Travis and then merge this in.

**Comment by dropfen** [comment]
Hey, that cool, thanks!

**Comment by dropfen** [comment]
How fast it usually on npm?

**Comment by timdorr** [comment]
It's whenever someone with publish access does a release. It'll be up there soon.

**Comment by dropfen** [comment]
Great, thank you!

**Comment by thedrew12** [comment]
Is this going to be on npm soon, my tests are breaking.

+1

**Pull request merged**
