### PR TITLE
react-router-config: passes exact and strict to Route in renderRoutes

### PR DESCRIPTION
**Pull request by kennethaa**

### CODE REVIEW

**Comment by pshrmn** [comment]
Dupe of #4728.

**Comment by kennethaa** [comment]
Sorry, forgot to check that. Closing.

**Comment by timdorr** [comment]
@kennethaa If you can add tests, we can merge this in place of #4728. Whomever does it first wins 😉

**Comment by kennethaa** [comment]
I'll see if I can find time, but probably not before sometime next week @timdorr :)

**Pull request closed without merging**
