### PR TITLE
Added server-side rendering example to new React Router Redux package

### PR DESCRIPTION
**Pull request by cereallarceny**
First of all: totally open to feedback here.  I needed server-side rendering to be done for [a variety of reasons](https://medium.com/@cereallarceny/server-side-rendering-with-create-react-app-fiber-react-router-v4-helmet-redux-and-thunk-275cb25ca972) with a client of mine.  I haven't found any sufficiently updated tutorials using `ConnectedRouter`, so I made one myself once I figured it all out.  I'm not sure of the correct copy to have in the readme itself, but I think the tutorial and codebase is helpful.

It's also been coded to be 100% independent of `create-react-app` meaning that you can drop it in your application and leave the use of it totally optional.  **This is both simultaneously an example of `ConnectedRouter` in both a client and a server-side setting.**

Please let me know how I can improve the copy and I'd be happy to make the changes!

### CODE REVIEW

**Comment by timdorr** [comment]
I'd much rather this code live here in the repo. Can you add it into your PR?

**Comment by cereallarceny** [comment]
Absolutely @timdorr - I'll get on that.  I'll separate the client-side example and the server-side example since they have the ability to live independent of one another.  Quick sanity check: am I correct in assuming that `ConnectedRouter` can be used on both the client and the server?  I'm used to using `BrowserRouter` and `StaticRouter` to differentiate environments, but I couldn't find direct documentation on when to use `ConnectedRouter`.  Is this a correct assumption?  My apologies if it's already stated in the docs and I just haven't seen it yet.

**Comment by cereallarceny** [comment]
@timdorr The new documentation is much more thorough, please let me know if this is more in line with what you were looking for.  I've created a full example for both the client and server flow all while doing my best to share resources between them (and cut down on duplication).  If this can be improved further, please let me know!

**Comment by cereallarceny** [comment]
Any chance of this getting merged @timdorr?

**Comment by timdorr** [comment]
Sorry, I let this one slip. Can we package this up as an example instead? I'd like the README to just have the basic usage listed and not get into specific examples.

**Comment by cereallarceny** [comment]
Not a problem @timdorr - I'm closing this PR in replacement of another.  You'll see I've moved everything into the examples folder and provided a link in the main readme to the other two examples provided.  Please see #5714.  Closing this PR in exchange for the new one.

**Pull request closed without merging**
