### PR TITLE
wrap text in a Link with a Text element

### PR DESCRIPTION
**Pull request by mihbor**
otherwise it throws Invariant Violation: React.Children.only expected to receive a single React element child.

### CODE REVIEW

**Comment by timdorr** [comment]
It doesn't throw anything. It's documentation and just a simple example of how to use it 😄

**Comment by mihbor** [comment]
My point was, if used as documented, it causes the invariant violation, hence the example needs correcting to work as expected.

**Comment by pshrmn** [comment]
I would merge this. Remembering to wrap all text in a `<Text>` element was my biggest gotcha when I started using RN, so we should have the correct syntax.

**Comment by pshrmn** [comment]
(or #6213, since that is the same PR 5 hours earlier. When it rains, it pours.)

**Comment by timdorr** [comment]
¯\\\_(ツ)\_/¯

OK.

**Pull request merged**
