### PR TITLE
path-to-regexp v2.0.0

### PR DESCRIPTION
**Pull request by pshrmn**
See https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23 for details on the changes to path-to-regexp

The biggest change is that instead of using `"/"` to match all pathnames, we should use `""`. This is because `/` and `/nested` are siblings (whereas `/nested` and `/nested/route` are parent/child paths).

Another change with this is that the wildcard route  is no longer supported. Instead, `(.*)` should now be used instead.

Finally, the trailing slash on a segment is now enforced (`/test/` no longer matches `/test`).

Moving discussion here from #5469.

### CODE REVIEW

**Comment by mjackson** [comment]
Hmm, I like the trailing slash changes but I'm not a fan of using the empty string to match `/`. I'd like to stay on 1.7 for now until I can dive further into this.

**Comment by pshrmn** [comment]
This should probably wait for React Router v5, and `path-to-regexp` v1 works well, so no rush to get this merged.

**Comment by timdorr** [comment]
Should we set up a `next` branch?

**Comment by pshrmn** [comment]
I'm going to close this for now because I'm not actually convinced that `path-to-regexp` v2 is better than v1. There are a couple things with v2 that are less straight forward (trailing delimiters, no more `*`) and the only API change that would be used by RR would be `endsWith`, but since we're already only matching against `location.pathname`, that should never be necessary.

Maybe at some point it will make sense to switch versions, but for now I think that `1.7.0` is good enough.

**Comment by dosentmatter** [comment]
@mjackson @timdorr, should you guys update the [docs](https://reacttraining.com/react-router/web/api/Route/path-string) ([on github](https://github.com/ReactTraining/react-router/search?utf8=%E2%9C%93&q=Any+valid+URL+path+that+path-to-regexp+understands.&type=)), to say that you use path-to-regexp `^1.7.0` instead of just saying
>Any valid URL path that path-to-regexp understands.

It will make it clearer for people since [path-to-regexp broke compatibility with older versions](https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x).

**Comment by dosentmatter** [comment]
@pshrmn okay, I'll do a PR. Just wanted to check first. Thanks!

**Comment by dosentmatter** [comment]
Made the PR at #6117.

**Pull request closed without merging**
