### PR TITLE
missing files in package.json

### PR DESCRIPTION
**Pull request by jfurie**
## Version
5.0.0-alpha.2 (react-router-redux)

## Test Case
Not sure how to test an npm pack
## Steps to reproduce

1. ` npm install react-router-redux@next`
2. include in project

## Expected Behavior
Run without breaking

## Actual Behavior

ERROR in ./~/react-router-redux/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./actions in /Users/joshfurie/hero.client/node_modules/react-router-redux
 @ ./~/react-router-redux/index.js 21:15-35

ERROR in ./~/react-router-redux/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./middleware in /Users/joshfurie/hero.client/node_modules/react-router-redux
 @ ./~/react-router-redux/index.js 70:18-41

### CODE REVIEW

**Comment by valstu** [comment]
Was just about to do the same PR. Related to #4694

**Comment by williamboman** [comment]
Was just hit by this one as well

**Comment by shawnmclean** [comment]
Is there a way to pull this change into my project? I can't seem to use the git repo because the project is nested.

**Comment by valstu** [comment]
@shawnmclean You can temporarily download this repo at this commit to your local environment then install react-router-redux with 'npm install --save file:Downloads/react-router/packages/react-router-redux/'. Section after 'file:' is the path where you downloaded/cloned this repo. After this gets merged remember to use react-redux-router from NPM.

**Comment by timdorr** [comment]
Thanks! 

BTW, please don't update the version from a PR. That will undoubtedly cause issues when pulling several PRs at once. And it signals a release when that hasn't necessarily happened.

**Pull request merged**
