### PR TITLE
refactor(Route):  simplify nested Ternary Conditional Operator

### PR DESCRIPTION
**Pull request by izayl**
It's hard to manage and understand use so many nested Ternary Conditional Operator.

So I refactor it to a more cleaner logic branch version.

### CODE REVIEW

**Comment by MeiKatz** [comment]
To be honest: instead of defining the method each time, define it as a class method and pass it the props as arguments. Also we should get rid of every ternary operator. Maybe the solution is something like the following:

**Comment by izayl** [comment]
@MeiKatz You're right, Thank you for your advice

**Comment by MeiKatz** [comment]
@izayl and now get rid of the remaining ternary operators ;)

**Comment by MeiKatz** [comment]
@izayl Thank you :+1:

**Comment by timdorr** [comment]
Eh, I don't want to get into the whole philosophical debate of ternary vs if/then. I've stated before that this form is more readable, but I know Ryan and Michael disagree. It’s a pedantic argument, so I don’t think it’s worth having yet again. I’ll leave it up to them if they want to accept this.

**Pull request closed without merging**
