### PR TITLE
Route Testing Example

### PR DESCRIPTION
**Pull request by pshrmn**
Added an example that lets you test how a `<Route>`'s props match against a URL

**Edit:** Updated gif for updated example
route-path-update

### CODE REVIEW

**Comment by timdorr** [comment]
Cool! I'd add some descriptive text at the top to explain what's going on with this. It might be a little opaque as to what's going on. Also, linking back to this in other parts of the docs would be useful.

Does the URL bar update as you type, or only after an Enter/blur?

**Comment by pshrmn** [comment]
If you're typing in the URL, it only updates after you hit <kbd>Enter</kbd>. It would be pretty easy to add a text input to continuously push new locations.

I was mostly tired of testing things out in the [live demo](http://forbeslindesay.github.io/express-route-tester/) that `path-to-regexp` links to, which is non-configurable and seems to be glitchy half the time I use it.

**Comment by mjackson** [comment]
This is a cool example, but feels kinda different from most of the others. I think the difference is that the others are focused on real use cases, but this one is a route path tester. I'd rather not have an example like that.

**Comment by pshrmn** [comment]
That's fine. As I mentioned above, I had just been tired of messing with the one linked to in the `path-to-regexp` repo, which didn't even seem to always work. The `examples` section was the only place that made sense to stick it on the site, but I can just host it on a `github.io` page.

**Comment by pshrmn** [comment]
[Barebones](https://pshrmn.github.io/route-tester/#/), but it works.

**Comment by timdorr** [comment]
It would be cool if this was inline with `<Route>`'s documentation.

**Pull request closed without merging**
