### PR TITLE
Adjusted `Route`'s PropTypes to accept a regular expression

### PR DESCRIPTION
**Pull request by JaffParker**
React Router's documentation states:

> ## path: string
> 
> Any valid URL path that [`path-to-regexp@^1.7.0`](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0) understands.

However, `path-to-regexp` officially support a RegExp as a parameter:

> - **path** An Express-style string, an array of strings, or a regular expression.

Technically, providing a `RegExp` as a `path` worked, but it would throw an error because of the PropTypes restriction. This pull request includes the necessary changes, the new test, and the corrected documentation.

A use case for that is something I just ran into: I needed to display something on all the pages _except_ for root, so I wrote a regexp that matches every string that has characters after the initial slash.

### CODE REVIEW

**Comment by MQuy** [comment]
Should we consider to support array?

**Comment by JaffParker** [comment]
I think array is a good idea, but not necessarily related here. Supporting
array is an all-new feature, whereas this is just an adjustment for
something that is already supported. I see this more as a bug fix.

**Comment by aeroheim** [comment]
FYI, this was mentioned in #5724 along with a workaround: 

> Overriding the path-to-regexp library by accepting custom regexp's is going to have unintended side effects. Instead, please use strings and the inline regexp match features of path-to-regexp.

I would love to have official support for custom RegExp though - I find it cleaner for the use case above instead of having to add an additional ```<Switch/>``` and ```<Route/>```.

**Comment by mjackson** [comment]
The main thing that keeps me from adding regexp support to `<Route path>` is that we won't be able to calculate a string for `match.path` anymore, which makes it hard (impossible?) to build relative `<Route>`s currently. This may change in the future, but for now I don't see a way around it. 😐

One thing that you may appreciate, however, is that we recently merged [support for an array of strings in `<Route path>`](#5889), which will probably let you do what you were trying to do with a regular expression in the first place. 😅

**Pull request closed without merging**
