### PR TITLE
Improve Initial Docs Experience

### PR DESCRIPTION
**Pull request by justsml**
Hi y'all, thanks to everyone for all the work that's gone into this library!!! 👍 

Here's a summary of my progress so far:

- [x] Add simpler "basic" example for "Quick Start."
- [x] Enhance (previous) nested routing example from "Quick Start."
- [x] Add explainer text to examples.
- [x] Move Philosophy to lower in the nav.
- [x] Quick Start is default content.

RE: #6409

### CODE REVIEW

**Comment by justsml** [comment]
For completeness, here's the before and after screenshots:

### Before
image

### After
image

**Comment by justsml** [comment]
Thanks for the 👍 @pshrmn @timdorr

**Comment by mjackson** [comment]
Thanks for the PR, @justsml! This looks great. I'll deploy it now.

**Comment by mjackson** [comment]
Should deploy as soon as https://travis-ci.org/ReactTraining/react-router/builds/445992237 is finished 👍

**Comment by mjackson** [comment]
Thank you for your contributions to the docs, @justsml :) A lot of people are going to benefit from the improvements you're making.

**Pull request merged**
