### PR TITLE
Hoist devDeps with Lerna

### LINKED ISSUE #4362: De-duplicate devDependencies
With the monorepo, each package is installing its `devDependencies` in its own `node_modules`. For me, this led to the `react-router` folder weighing in at ~234MB. A lot of these are duplicated across packages and should be able to be moved to the root `package.json`. The only ones that can't, as noted by the [lerna documentation](https://github.com/lerna/lerna#common-devdependencies) are the ones that need binaries to run (i.e., `karma`).

For reference, across each `package.json` each dependency is included the following number of times:

| Package | Count |
| --- | --- |
babel-cli | 2 
babel-core | 1
babel-eslint | 2
babel-loader | 3
babel-plugin-dev-expression | 2
babel-plugin-transform-react-remove-prop-types | 2
babel-preset-es2015 | 3
babel-preset-react | 3
babel-preset-stage-1 | 3
bundle-loader | 1
copy-webpack-plugin | 1
css-loader | 1
eslint | 2
eslint-plugin-import | 2
eslint-plugin-react | 2
expect | 2
file-loader | 1
gzip-size | 2
html-loader | 1
html-webpack-plugin | 1
in-publish | 2
jsxstyle | 1
karma | 2
karma-browserstack-launcher | 2
karma-chrome-launcher | 2
karma-mocha | 2
karma-mocha-reporter | 2
karma-sourcemap-loader | 2
karma-webpack | 2
markdown-it | 1
markdown-it-anchor | 1
mocha | 2
postcss-loader | 1
pretty-bytes | 2
prismjs-loader | 1
react | 4
react-addons-test-utils | 2
react-dom | 3
react-motion | 1
react-native | 1
readline-sync | 2
style-loader | 1
sw-precache | 1
sw-precache-webpack-plugin | 1
url-loader | 1
webpack | 3
webpack-dev-server| 3

### PR DESCRIPTION
**Pull request by timdorr**
Fixes #4362

### CODE REVIEW

**Comment by timdorr** [comment]
BTW, I was having some issues with this locally. We'll see if Travis can get through it. It might be buggy since it's all new and beta and such.

**Comment by mjackson** [comment]
🎉  Thanks, @timdorr! Was just sitting down to do this myself.

**Comment by mjackson** [comment]
Darn, I can't get beta.35 to work for me locally. Here's what I get

```
$ npm i

> react-router-packages@ postinstall /Users/michael/Projects/react-router
> lerna bootstrap

Lerna v2.0.0-beta.35
Bootstrapping 4 packages
Preinstalling packages
Installing external dependencies
FileSystemUtilities.rimraf    ("./packages/react-router-dom/node_modules/babel-cli")
Command exited with status -2: /Users/michael/Projects/react-router/node_modules/lerna/node_modules/.bin/rimraf /Users/michael/Projects/react-router/packages/react-router-dom/node_modules/babel-cli
Errored while running BootstrapCommand.execute
Command exited with status -2: /Users/michael/Projects/react-router/node_modules/lerna/node_modules/.bin/rimraf /Users/michael/Projects/react-router/packages/react-router-dom/node_modules/babel-cli
Waiting for 2 child processes to exit. CTRL-C to exit immediately.
```

@timdorr Is that the issue you were seeing? Gonna roll back to lerna.32 and try to get tests passing.

**Comment by timdorr** [comment]
Yep, I got a few variations of that same thing despite all the options I chose. I was going to open an issue with Lerna, unless you have already.

**Pull request merged**
