### PR TITLE
Fix documentation for nested routing

### PR DESCRIPTION
**Pull request by Eisermann**
You need to use `component={xxx}` syntax, otherwise match will be `undefined`.

### CODE REVIEW

**Comment by MeiKatz** [comment]
Nope, there is a pending of mine from yesterday fixing this incorrect behaviour: #6951

**Comment by timdorr** [comment]
Yeah, let's get #6951 in. The docs should be correct.

**Comment by timdorr** [comment]
Let's get this in then.

**Comment by mjackson** [comment]
My fault, I prematurely updated those docs without updating the `Topic` and `Topics` components. Will do that today.

**Pull request merged**
