### PR TITLE
Removing "update blocking" content

### PR DESCRIPTION
**Pull request by bradwestfall**
@mjackson Just wanted to be sure this is all the content you wanted removed. Besides the "update blocking" page itself, two other pages made reference to it.

### CODE REVIEW

**Comment by timdorr** [comment]
Can this get rebased against the latest website branch?

**Comment by bradwestfall** [comment]
Yes, are you asking if it should be done or for me to do it? 

Michael asked me to update the content and this was my first go with the router->website workflow so I just made the PR so he could check the work to make sure I didn't break it. But he's been super busy with that workshop tour. So if you wanted to review/rebase/merge that would be great

**Comment by timdorr** [comment]
If you don't mind. I can take care of the review and merge.

**Comment by bradwestfall** [comment]
Perfect, thank you

**Comment by timdorr** [comment]
Confirmed it looked good locally. I'll wait for Travis and then merge it in.

**Comment by damir-sirola** [comment]
Hi, I found this page to be very helpful as I encountered the problem with my components not rendering. The reason is described very well in the deleted page. If you are able to provide some context about why it was removed it I would really appreciate it?

**Comment by bradwestfall** [comment]
The docs generally reflect the latest version, in version 5 the problem isn't there anymore. In fact, v5 is basically the same API as 4 but with some internal fixes like this so migrating should be easy. Checkout this which Michael wrote about it https://reacttraining.com/blog/react-router-v5/

**Comment by damir-sirola** [comment]
Thank you for the answer

**Pull request merged**
