### PR TITLE
Correctly infer the read only type

### PR DESCRIPTION
**Pull request by Domino987**
This PR adds a generic to readOnly to return the passed in object type.

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks, but `Object.freeze` accepts any type as input, so this is valid as-is.

**Comment by Domino987** [comment]
@timdorr But you want to return the same type correct? So whatever you pass in, should be the same passed back out right? Because currently, the return type is any, not the type passed in. But it is actually that type, that was passed.

**Comment by timdorr** [comment]
Sure, but we should support `any` type being passed in. Can we modify this to `extends unknown` to better represent this?

**Comment by Domino987** [comment]
Yes I was thinking the same thing.

**Comment by timdorr** [comment]
OK, thanks!

**Pull request merged**
