### PR TITLE
Pass transition hook's arguments correctly

### PR DESCRIPTION
**Pull request by arkist**
I've reported #4114 but nobody responded.
eventually, I fixed it myself. 😂 

Hope you guys are happy with this. 🙏

### CODE REVIEW

**Comment by arkist** [comment]
@timdorr Thanks for respond! 
I Added simple test case and updated code.

close and reopen issue for trigger ci build. 
it's failing on (ie|mobile safari) sometimes but not because of my change. weird. 🤔

**Comment by timdorr** [comment]
I believe because you're the author of the PR, you should see a restart build button in Travis. So, you shouldn't have to close/re-open the PR to trigger a build. It should also pick up on force pushes. You don't have to rebase either, as my usual thing is to squash and merge, so any extraneous commits get cleaned up anyways.

**Comment by arkist** [comment]
@timdorr Thank you for explaining. I will try in next time. 😄 
do you have any release plan for this?

**Comment by cyanic-webdesign** [comment]
This is breaking my unit test which was working in 2.8. So 👍  for releasing this. Could probably be a patch release since this is a fixed bug.

**Pull request merged**
