### PR TITLE
Added async render to Route component

### PR DESCRIPTION
**Pull request by codejamninja**
Let people asynchronously render react router routes

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks, but this is the something we're going to implement within the router. Also, this would break every single user of the existing API, as it becomes async-only. Again, there are many ways of handling this in userspace without changes to the library.

**Comment by codejamninja** [comment]
Actually this wouldn't break existing users. You can await a non async function.

**Comment by codejamninja** [comment]
You keep saying there are many ways of handling this, but I can't find any way that doesn't require deferring the router from switching. Can you please direct me to these "many ways" or else acknowledge the problem?

**Comment by pshrmn** [comment]
It was a typo, he meant "not going to implement".

`React.lazy` will let you automatically asynchronously load components without React Router having to do anything.

**Comment by codejamninja** [comment]
Ok thanks

**Pull request closed without merging**
