### PR TITLE
fix(useParams): fix issue with useParams reading from null object

### LINKED ISSUE #6938: Issue with `useParams` hook on unmounted component
# Version

5.1.0

## Test Case

https://codesandbox.io/s/jolly-field-rm0sb

## Steps to reproduce

Use the `children` prop on a `<Route />` to render a component. 

## Expected Behavior

Like with accessing `match` off of props, `useParams()` should return `null` or an empty object.

## Actual Behavior

`useParams` errors when reading property off null.

### PR DESCRIPTION
**Pull request by brandon-pereira**
fixed by returning empty object if route not mounted

Closes #6938

### CODE REVIEW

**Comment by timdorr** [comment]
@mjackson Is this what you envision being returned from `useParams` if there is no `match`?

**Comment by MeiKatz** [comment]
I think returning `null` in this case is unexpected for me. The solution seems reasonable to me.

**Comment by brandon-pereira** [comment]
@timdorr I've added tests and pushed the changes! 

@MeiKatz Perfect! Glad we agree on this.

**Comment by timdorr** [comment]
Cool, I'm going to merge this in as-is. If it's not what was expected, I'll put in a fix myself. Thanks!

**Comment by mjackson** [comment]
This was released in 5.1.1

**Pull request merged**
