### PR TITLE
Add history to the repo

### PR DESCRIPTION
**Pull request by mjackson**
It made its way all the way back! :D

### CODE REVIEW

**Comment by timdorr** [comment]
Sooooo, is this still happening?

**Comment by mjackson** [comment]
Yep. NEED MOAR TIIIIIIME..

**Comment by mjackson** [comment]
I'll try to close out all existing PRs on ReactTraining/history this week and merge it in here before I cut a new release. Looks like we're due for another minor release at this point. Thanks for the prod, @timdorr

**Comment by mjackson** [comment]
On second thought, I'm gonna leave history as its own repo. The tests are different enough that I don't wanna mix 2 test harnesses.

**Pull request closed without merging**
