### PR TITLE
react-router-config - renderRoutes(routes, otherProps = {})

### PR DESCRIPTION
**Pull request by jharris4**
Add optional otherProps argument to react-router-config's renderRoutes function.

I'm working on migrating a rather complex project from react-router 3.x to 4.x, and I need the ability to pass props from a parent route's component to all child routes' components.

Adding the otherProps as an optional argument to renderRoutes allows me to do this...

### CODE REVIEW

**Comment by jharris4** [comment]
I'm happy to add an entry in `CHANGES.md`, but I'm a bit of a n00b when it comes to lerna packages. Should I create a new changelog within the `packages/react-router-config` directory, or just edit the one in the root directory?

**Comment by timdorr** [comment]
Anything meta (version bumps, changelog entries, etc) don't belong in PRs, so don't worry about that.

**Comment by jharris4** [comment]
Sure, I actually had to edit the PR description because I mistakenly thought I had called it extraProps. :-)

Are there existing tests for `react-router-config` somewhere that I missed?

**Comment by jharris4** [comment]
Tests added, thanks for the feedback. Let me know if there's anything else I can do.

**Comment by timdorr** [comment]
Thanks! LGTM. I don't know if I should wait for a second +1 since it's still beta, but I'll merge it in a couple days if there are no objections.

**Comment by vilsad** [comment]
have you merged this feature ?

**Comment by sungwoncho** [comment]
@timdorr this is a useful feature that is hindering me from fully migrating to v4. I was about to begin working on the same PR. I would like to see this merged.

Anything I can do to help ship this?

**Comment by timdorr** [comment]
If someone can resolve those merge conflicts, I can merge this in. Sorry, I forgot about this PR!

**Comment by jharris4** [comment]
I'm trying to merge, but wow talk about merge hell. The refactoring of the tests to Jest is making life interesting.

I'm currently stuck on errors when running tests, related to resolving jest_cli from node_modules.

Can anyone else do a pull from master and confirm that they can do `npm install` followed by `npm test` ?

**Comment by jharris4** [comment]
@timdorr ok, merged conflicts fixed.

Please merge to master ASAP ;-)

**Comment by timdorr** [comment]
Thanks!

**Comment by adamrneary** [comment]
@jharris4 thanks for this!
@timdorr i think this might be necessary to make animations work with `react-router-config` as you need to pass the location and a key to through to the child component. do you have a sense for when this might make a release? 

Thanks so much!

**Comment by jharris4** [comment]
@adamrneary Happy to see other people are finding the need for the same functionality! ;-)

FWIW the renderRoutes code is so short, that I worked around it by adding a local copy like so:

```
// TODO - remove local version once react-router/pull/5137 is merged and released
// import { renderRoutes } from 'react-router-config';
import { Switch, Route } from 'react-router';
const renderRoutes = (routes, extraProps = {}) => routes ? (
  <Switch>
    {routes.map((route, i) => (
      <Route key={i} path={route.path} exact={route.exact} strict={route.strict} render={(props) => (
        <route.component {...props} {...extraProps} route={route}/>
      )}/>
    ))}
  </Switch>
) : null;
```

**Comment by D34THWINGS** [comment]
When will this be released ? Thanks for your work !

**Comment by jharris4** [comment]
@D34THWINGS looks like this was just released in 1.0.0-beta.4

@timdorr Any chance you're going to add this to the release notes page?

**Comment by jharris4** [comment]
@timdorr Oh, it is mentioned in the `react-router` `4.2.0` notes.

Kind of confusing since it's in a separate package... I also missed it because the title still says `otherProps` instead of `extraProps`. lol

**Pull request merged**
