### PR TITLE
withRouter higher order component 

### PR DESCRIPTION
**Pull request by alisd23**
For #3847

Currently passes down the following props:
- `location`
- `history` _(excluding location_) - includes history methods (push, go, listen etc...)
- `router`

Just thought I'd get a PR created to start a discussion on the specifics (or if we want one at all).

Todo:
- [x] Add `withRef`, `displayName`, `hoistStatics` functionality
- [x] Add tests
- [ ] Update docs

### CODE REVIEW

**Comment by timdorr** [comment]
There's a couple things needed here. Check [the v3 HoC](https://github.com/ReactTraining/react-router/blob/v3/modules/withRouter.js).

- `withRef` support to get a ref to the wrapped component.
- `displayName` support.
- `hoistStatics` so that things like data loading statics and others are still available after wrapping.

**Comment by alisd23** [comment]
Do you agree with the `props` being passed down: `history`, `location`, and `router`?

**Comment by timdorr** [comment]
Yes, but you'll also need to pass through params (which you should already be doing).

**Comment by alisd23** [comment]
Params are passed as a separate prop to `Match` components already yes

**Comment by alisd23** [comment]
I've gone with the `withRouter(options)(Component)` API as opposed to the `withRouter(Component, options)` API, as this lets `withRouter` be fully used as a decorator

```js
// With options
withRouter(options)(Component)
// OR
@withRouter(options)
class Component {}

// Without options
withRouter(Component)
// OR
@withRouter
class Component {}
```

I'd be interested to hear of any caveats if there are any, or if anyone thinks you should **always** have to supply an options argument, making the simplest decorator usage: `withRouter()`.

**Comment by ryanflorence** [comment]
I'd like to only see `location` and `router` passed, exactly as they are on context. Not history though.

**Comment by alisd23** [comment]
I think one of the main use cases for this was to be able to access history methods like `go`/`goBack` and `replace`. If we don't pass `history`, devs will have to make their own `withRouter` HOC which gets history off context, or just grab it off context in each component.

**Comment by jochenberger** [comment]
I already have use cases for `router`, `location` and `history`. I acquire them all from the `context` at the moment.

**Comment by oncletom** [comment]
I agree `history` is useful. I often use the `.listen` to make the app to react to browser location change.

**Comment by alisd23** [comment]
@ryanflorence what are your current thoughts about passing history down as well? I really think we should allow the user access to the `history` methods through here, and I think it's okay to expose internal stuff here as I see `withRouter` as more of an *advanced* feature.

Even though requiring the history object is not the common case, I think we should make it easy to access for the few that really do need it.

**Comment by porfirioribeiro** [comment]
It should also pass params, the withRouter component might not be a direct descendent of the Match.
You may hae a generic component that needs to access router, params and history.

**Comment by just-boris** [comment]
After the commit https://github.com/ReactTraining/react-router/commit/935649e60762ece415282f139345f14c3cc992aa with a comprehensive message "some refactoring", this pull request will not work, because `Broadcast` has gone.

See [the new `Link` implementation](https://github.com/ReactTraining/react-router/blob/f92465a4055639dc412ede31d95888fa778e3f9e/modules/Link.js#L35) to get the idea how to read location in a new way.

Summon @ryanflorence to help to push this forward.

**Comment by mjackson** [comment]
I'm afraid this PR is a bit outdated. We've got a `withHistory` HOC in current v4 that should do what you need, except for the `hoistStatics` bit. Please take a look and holler if it's not adequate.

**Comment by nzjoel1234** [comment]
@mjackson Although the `withHistory` HOC does provide what I require (match, location, push etc.) I find it a bit confusing the the history object is spread directly into the params.
My main concern is the naming of the history methods being confusing out of context.
I.e I would prefer to write:
```
const { history } = this.props;
...
history.push(...);
```
Over:
```
const { push } = this.props;
...
push(...);
```
I find the first case to be more obvious about what is going on.

**Comment by pshrmn** [comment]
@nzjoel1234 `withRouter` now passes three props to the component it wraps: `history`, `match`, and `location`. You can read more about it in the [documentation](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/withRouter.md). The code that does this is not yet released, but it is on the way,

**Comment by biganth** [comment]
Docs corrected link: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/api/withRouter.md

**Comment by Hookkid** [comment]
@biganth the docs link is down again.. :(

**Comment by YasserKaddour** [comment]
@Hookkid the docs are here https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md 😃

**Pull request closed without merging**
