### PR TITLE
TypeScript build support

### PR DESCRIPTION
**Pull request by Therealnaxos**
This is an attempt to add TypeScript support,
so that types are exported and can be used by
projects to get type definitions.

Only the source itself is converted to Typescript,
no tests are configuration files (as that seems to
be unnecessary just for the goal of getting type
definitions)

This adds some lines to the build script to generate
type definitions (after building the actual library).
For rollup, the typescript preset is used with babel so
that the types are simply removed during that stage.

To run tests, jest should not pick up the index.tsx files,
as it should only look in the build directory for modules,
but somehow it does. Attempts to add the .tsx files to a
variety of ignore patterns were unsuccesful so far.

To be resolved:
- [ ] remaining type errors on the index.tsx source
- [ ] jest config to ignore tsx

Solves #6955

### CODE REVIEW

**Comment by ayush987goyal** [comment]
We can consider to use `rollup-plugin-typescript2`. That would mean we would not any any `babel` transformers. This one plugin would be sufficient enough. We will still have prettier, terser etc. plugin though.

**Comment by lekoaf** [comment]
I'm having trouble typing `MemoryRouter`.

According to [documentation](https://reacttraining.com/react-router/web/api/MemoryRouter/initialentries-array) `initialEntries` can either be an array of strings or an array of objects (`Location`). The trouble is `createMemoryHistory()` only accepts arrays of strings. How would we solve this conundrum?

**Comment by mjackson** [comment]
Thanks for taking the time to take a look at this, @Therealnaxos. I just wanted to say up front that I'm not 100% certain we will convert all of the code to TypeScript. I think a good place to start might be to include a hand-written `.d.ts` file with each package that we publish. I haven't been very happy with `tsc`'s auto-generated type definitions.

**Comment by xiaoxiangmoe** [comment]
@mjackson We can use [API Extractor](https://api-extractor.com/) to generate type definitions bundle.

**Comment by xiaoxiangmoe** [comment]
The code here does not enable `strict:true` in tsconfig. Can I can pick this and rewrite a version with full type checking?

**Comment by xiaoxiangmoe** [comment]
Hi, all. I fix all type errors for react-router-dom in https://github.com/ReactTraining/react-router/pull/7269.
@mjackson Please have a look and tell me if I need to continue. Thank you very much.

**Comment by mjackson** [comment]
Hi all, I have a PR in #7292 that is my attempt at converting the source to TypeScript. It was fairly involved, and I had to touch the build + test code as well, so it probably wasn't a good candidate for a PR from a first-time contributor. But I really appreciate you getting the ball rolling here @Therealnaxos 😅

If you'd like to review my work, please feel free. Thanks!

**Pull request closed without merging**
