### PR TITLE
Support for relative path routes

### PR DESCRIPTION
**Pull request by karevn**
I've added a little cleanups on top of Lukas' work.

### CODE REVIEW

**Comment by karevn** [comment]
As far as I understand, Travis checks fail due to the problem discussed here: https://github.com/ReactTraining/react-router/issues/6201

To make it build correctly, we should add `cd packages/react-router && npm install` to the build script, so correct `path-to-regexp` version will be installed and used by tests.

**Comment by yordis** [comment]
@karevn just for being in the same page. What is your implementation look like from routing perspective?

**Comment by yordis** [comment]
@karevn OMEGALUL sorry.

How will the routes look like? Could you share in the description how the final implementation will look like

**Comment by mjackson** [comment]
Hi @karevn, thanks for the PR. Would you mind rebasing on current master?

**Comment by mjackson** [comment]
Looks like this PR is stale. Closing.

**Comment by yordis** [comment]
@mjackson wouldn't be better to continue the work by rebasing against `master`? From code review what is left?

**Comment by karevn** [comment]
Looks like I've missed previous comments. @mjackson are you still interested?

**Pull request closed without merging**
