### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xiangzhuyuan**
change outdated URL link

### CODE REVIEW

**Comment by xiangzhuyuan** [comment]
looks like `reactjs/react-router` redirect to `ReactTraining/react-router`, but that tutorial haven't redirect to here

**Comment by timdorr** [comment]
The link is correct as-is.

**Comment by xiangzhuyuan** [comment]
@timdorr 
what I try to fixed just like one: https://github.com/ReactTraining/react-router/issues/3832

could you check that?

**Comment by timdorr** [comment]
Oh, shit. My bad. Yeah, this was right. One sec...

**Comment by xiangzhuyuan** [comment]
@timdorr thanks! have a nice day~

**Pull request merged**
