### PR TITLE
v4 Context API Docs

### PR DESCRIPTION
**Pull request by SimeonC**
PR for #4134

### CODE REVIEW

**Comment by giannif** [comment]
@SimeonC seems like there might be a few [additions](https://github.com/ReactTraining/react-router/blob/v4/modules/StaticRouter.js#L57)? `getState`, `onMatch`, `subscribe`

**Comment by vramana** [comment]
It seems that `history` is not exposed on context anymore.

**Comment by mjackson** [comment]
I'm afraid this PR is a bit out-dated. v4 is settling down now, so you'll have much better luck getting something merged if you take a look at the current code.

**Comment by SimeonC** [comment]
Thanks for letting me know, I'll look at it when I can.

**Pull request closed without merging**
