### PR TITLE
[Experimental] Flip startTransition and isPending

### PR DESCRIPTION
**Pull request by phaux**
facebook/react#20976

### CODE REVIEW

**Comment by timdorr** [comment]
Is this released anywhere yet? I know it's an unstable API, so things can change whenever they want. But just so folks using this don't run into trouble.

**Comment by phaux** [comment]
It's already released as latest experimental version. The last version that works with `react-router-dom@experimental` is `{react,react-dom}@0.0.0-experimental-78120032d`.

**Comment by damikun** [comment]
This is not yet part of React router...

**Comment by RichardLindhout** [comment]
There are even more changes unstable_ prefixes got removed

**Comment by damikun** [comment]
@RichardLindhout  What I know transition is still `unstable_`  other one gets stable with lastest React but transition not.. Only if this changed in last days...

**Comment by RichardLindhout** [comment]
In the experimental release I'm importing straight from   React.useTransition but I'm using ```^0.0.0-experimental-46491dce9``` maybe they've changed it back to unstable

**Comment by damikun** [comment]
Are you using typescript and last Types? I remember i was updating types month ago for this... But maybe I should check correctly again :P  But good to know the import is directly available...

**Comment by phaux** [comment]
Updated React again. `react-test-rendered` is not the latest because it fails.

**Comment by RichardLindhout** [comment]
> Are you using typescript and last Types? I remember i was updating types month ago for this... But maybe I should check correctly again :P But good to know the import is directly available...

Types were not up to date yet I think. Btw React 18 is now released so hope react-router will update soon :)

**Comment by timdorr** [comment]
Can we bump this to the `@alpha` releases, now that they are out? That should be a more stable target. Thanks!

**Comment by phaux** [comment]
Updated and now it warns about not using `ReactDOM.createRoot`, but when I change it then it fails. `react-test-renderer` still fails with alpha version so I left it at last experimental version that works.

**Comment by timdorr** [comment]
Did you use `React.createRoot().render()`? That's the new API (you create a root and then render or hydrate it)

**Comment by phaux** [comment]
> Did you use `React.createRoot().render()`? That's the new API (you create a root and then render or hydrate it)

Yes, like that:

```diff
 act(() => {
-  ReactDOM.render(
+  ReactDOM.createRoot(node).render(
     <Router initialEntries={['/home']}>
       <Routes>
         <Route path="home" element={<Home />} />
         <Route path="about" element={<About />} />
       </Routes>
     </Router>,
-    node,
   );
 };
```

And I get error:

```
/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:1543
    return doc.body;
               ^

TypeError: Cannot read property 'body' of null
    at getActiveElement (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:1543:16)
    at getActiveElementDeep (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:8017:17)
    at getSelectionInformation (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:8050:21)
    at prepareForCommit (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:10500:26)
    at commitBeforeMutationEffects (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:21737:27)
    at commitRootImpl (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:25273:45)
    at commitRoot (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:25168:5)
    at finishConcurrentRender (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:24511:9)
    at performConcurrentWorkOnRoot (/home/lis/code/react-router/node_modules/react-dom/cjs/react-dom.development.js:24389:5)
    at workLoop (/home/lis/code/react-router/node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:253:34)
    at flushWork (/home/lis/code/react-router/node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:226:14)
    at Immediate.performWorkUntilDeadline (/home/lis/code/react-router/node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:516:21)
    at processImmediate (internal/timers.js:461:21)
```

**Pull request closed without merging**
